import type { Metadata } from 'next'
import { Nunito } from 'next/font/google' // Import the Nunito font
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const nunito = Nunito({ subsets: ['latin'] }) // Set up the Nunito font

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} flex flex-col min-h-screen bg-white`}>
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
